# TODO: generate keys and update creation rules dynamically on nixos-anywhere install (update yaml with yq)
keys:
  - &master age1nww8elvlr7l2sn2452z6wef8tyex53ehrypemkxhzfay2t99x52scwsw94
  - &user_shorty age10a049meemjvgdgukx6zu5lwu82mqul83l7fyd66tzy9sm8637s7q07ujez
creation_rules:
  - path_regex: hosts/shared/secrets/.*
    key_groups:
      - age:
          - *master
          - *user_shorty
  - path_regex: hosts/luna/secrets/.*
    key_groups:
      - age:
          - *master
          - *user_shorty
  - path_regex: hosts/luna/users/shorty/secrets/.*
    key_groups:
      - age:
          - *master
          - *user_shorty
  - path_regex: hosts/mars/secrets/.*
    key_groups:
      - age:
          - *master
          - *user_shorty
  - path_regex: hosts/mars/users/shorty/secrets/.*
    key_groups:
      - age:
          - *master
          - *user_shorty
