keys:
  - &master age1hy523tlslqas8qgs0lxgxanp9gx06fjekn608w4qf66mxkjzmucqh0g6vg
creation_rules:
  - path_regex: hosts/shared/secrets/.*
    key_groups:
      - age:
          - *master
  - path_regex: hosts/luna/.*/secrets/.*
    key_groups:
      - age:
          - *master
  - path_regex: hosts/luna/users/shorty/secrets/.*
    key_groups:
      - age:
          - *master
